- poetry.lock
- pyproject.toml
Fixes: https://github.com/Nitrokey/nitrokey-sdk-py/security/dependabot/1
> Bump black to 24.3

- poetry.lock
- pyproject.toml
spsdk does not contain breaking changes in those parts of the API that we use so we can relax our dependency constraint.  This also allows us to update the locked cryptography version to 42.0.8, fixing some security issues.
> Support spsdk 2.2

- .github/workflows/ci.yaml
Users will install this package via pip, not poetry.  This patch adds a CI job to ensure that the installation via pip works too.
> ci: Add test using pip

- .github/workflows/cd-pypi.yaml
- .gitignore
Based on:
https://github.com/Nitrokey/nitrokey-app2/blob/8a5ff1bcbeb004bfada5087938c2b22cf67410b5/.github/workflows/cd-pypi.yaml
Fixes: https://github.com/Nitrokey/nitrokey-sdk-py/issues/10
> ci: Add release workflow for PyPI

- .github/workflows/cd-pypi.yaml
While at it, rename publish-binary to publish because we’re also publishing source code.
> ci: Fix indentation of publish job

- .github/workflows/cd-pypi.yaml
Using environments allows to configure additional protections for the secret, e. g. manual approval of the publish workflow.
> ci: Use PyPI environment for publish job

- CHANGELOG.md
- src/nitrokey/trussed/admin_app.py
"frontport" of https://github.com/Nitrokey/pynitrokey/pull/556
> And random generator and config failures to init status bytes

- .github/workflows/ci.yaml
- src/nitrokey/trussed/_bootloader/nrf52_upload/lister/unix/unix_lister.py
This PR extends the job running the test suite for an pip installation to run on all supported platforms and with all supported Python versions.
The new CI configuration exposes a missing import in the `nrf52_upload` module on Windows that is also fixed by the PR.
> Test installation with pip on all supported systems

- .github/workflows/ci.yaml
- .github/workflows/full.yaml
The full compatibility tests with all Python versions on all operating systems lead to a significant slowdown when multiple workflows are running.  With this patch, we only run tests with Python 3.9 on the three operating systems.  The full tests are run once a day or after a manual trigger (e. g. before a release).
> ci: Remove full compatibility tests from default workflow

- poetry.lock
Fixes: https://github.com/Nitrokey/nitrokey-sdk-py/security/dependabot/6
> Update locked dependencies

- CHANGELOG.md
- src/nitrokey/nk3/updates.py
This PR removes the two step update handling on macOS, which required to invoke the update command twice.
Additionally it corrects a typo in an update message.
> Remove two step update handling on macOS

- .github/workflows/ci.yaml
- ci-scripts/linux/rpm/protobuf.patch
- ci-scripts/linux/rpm/python3-nitrokey.spec
This PR updates the RPM build in preparation for the next release.
Detailed changes:
- Update `protobuf.patch`, due to changes in `pyproject.tom`. Also now takes the changes in `poetry.lock` into account.
- Add a new build dependency which is required if the Poetry build backend should be used.
- Add more dependencies to RPM version accordance check in CI pipeline. Change due to new released Fedora version.
> Update RPM build

- .github/workflows/cd-pypi.yaml
- .github/workflows/ci.yaml
Poetry is already restricted to >=1,<2 in pyproject.toml.  This patch adds the same restriction to the CI.  This makes sure that we don’t get warnings in the CI because poetry 2.0.0 wants us to migrate our pyproject.toml file.
> Restrict poetry version in CI

- CHANGELOG.md
- src/nitrokey/nk3/_device.py
- src/nitrokey/nkpk.py
- src/nitrokey/trussed/_device.py
This PR fixes the "wrong channel" error when accessing different device models after listing them.
Detailed changes:
- Changes `list` method on `TrussedDevice` to abstract.
- Implement `list` on `NK3` and `NKPK`.
- Uses the same mechanic for the device listing as the implementations for the bootloader devices.
Partly fixes #31
> Open only CtapHid device for the respective Nitrokey

- .github/workflows/cd-pypi.yaml
- CHANGELOG.md
This patch changes the CD workflow to use trusted publishing to PyPI. The main changes are:
- The CD workflow is always executed and always publishes to TestPyPI.
- For releases, the workflow also publishes to PyPI.
- Instead of using access tokens, we use a GitHub environment for the publication jobs.  This environment is configured on TestPyPI/PyPI and release jobs running in that environment can publish releases.
---
TestPyPI works, PyPI still needs to be configured and tested.
> Use trusted publishing for PyPI

- .github/workflows/ci.yaml
- CHANGELOG.md
- Makefile
- ci-scripts/linux/rpm/python3-nitrokey.spec
- pyproject.toml
This release candidate fixes concurrent access to different models and tests trusted publishing to PyPI.
> Release v0.2.4-rc.1

- .github/workflows/cd-pypi.yaml
This fixes two problems with the PyPI CD:  It did not handle prereleases, and the `github.event.name` filter did not work.
It now uses `types: [published]` as a trigger as recommended here: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
And it uses `github.event_name` as a filter as documented here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
> Fix PyPI CD

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- src/nitrokey/nk3/updates.py
- tests/__init__.py
This patch adds support for updating the Nitrokey 3 to firmware v1.8.2 or newer by adding the required checks for the migration of the internal filesystem to version 2 (FIDO2 RK flattening).  The main changes are:
- Remove `UpdatePath` and related functions from the public API as these are implementation details of the `Updater`.
- Replace the single `UpdatePath` with a set of `Migration`s to reflect the fact that there can be multiple migrations happening at once.
- Try to run the migration checks early if possible – otherwise we can be in a situation where the update fails due to missing IFS space, the device stays in bootloader mode and re-running the update skips the checks because the device is in bootloader mode.
- Add a warning when updating from bootloader mode.
For discussion:
1. …
> Add support for updates to Nitrokey 3 v1.8.2

- docs/conf.py
- docs/index.rst
- pyproject.toml
This patch adds a custom substitution to the Sphinx conf.py that makes it possible to reference the SDK version in the docs.  This is necessary for the integration into docs.nitrokey.com where we cannot use the version setting to indicate the package version.
Fixes: https://github.com/Nitrokey/nitrokey-sdk-py/issues/64
----
This means that the version will show up in the navigation on docs.nitrokey.com but I think that’s fine.  Alternatively, we could add it to the body only.
> docs: Add package version to index

- CHANGELOG.md
- src/nitrokey/nk3/updates.py
- src/nitrokey/trussed/_bootloader/__init__.py
We already support setting a minimum pynitrokey version.  This is no longer useful after extracting the update logic into the SDK, so this patch introduces a minimum SDK version requirement that replaces the pynitrokey version requirement if set.  The current SDK version is determined with importlib.metadata.version.
> Add support for a minimum SDK version for firmware updates

- CHANGELOG.md
- ci-scripts/linux/rpm/python3-nitrokey.spec
- pyproject.toml
- src/nitrokey/nk3/updates.py
This release extends the nitrokey.nk3.updates module and adds support
for updating to Nitrokey 3 firmware v1.8.2.
> Release v0.3.0

- .github/workflows/ci.yaml
This fixes an issue with virtualenv 20.31.0 and Poetry 1, see: https://github.com/python-poetry/poetry/issues/10378
> ci: Use Poetry 2 for updating

- CHANGELOG.md
- src/nitrokey/nk3/updates.py
- src/nitrokey/trussed/admin_app.py
Added  in https://github.com/Nitrokey/nitrokey-3-firmware/pull/621
> Add init status EFS_FLASH_NEED_REFORMAT

- CHANGELOG.md
- docs/api/nitrokey.nk3.rst
- docs/api/nitrokey.nk3.updates.rst
- docs/api/nitrokey.trussed.rst
- docs/api/nitrokey.trussed.updates.rst
- src/nitrokey/nk3/_bootloader.py
- src/nitrokey/nk3/_device.py
- src/nitrokey/nkpk.py
- src/nitrokey/trussed/__init__.py
- src/nitrokey/trussed/_base.py
- src/nitrokey/trussed/_bootloader/__init__.py
- src/nitrokey/trussed/updates.py
- tests/__init__.py
This patch moves the nk3.updates module to trussed.updates and makes it
independent of the model.  This is a preparation for applying NKPK
firmware updates.
> Refactor nk3.updates to trussed.updates

- Makefile
Poetry v2 replaced `install --sync` with the `sync` command and made the `--no-update` option the default for the `lock` command, see:
https://python-poetry.org/blog/announcing-poetry-2.0.0/
> Update Makefile for poetry v2

- CHANGELOG.md
- src/nitrokey/trussed/admin_app.py
- tests/__init__.py
Zero is a valid U8 value.  This patch also adds basic tests for ConfigFieldType.is_valid.
> trussed.admin_app: Fix validation of ConfigFieldType.U8 values

- CHANGELOG.md
- src/nitrokey/trussed/updates.py
This PR adds default values to `Updater.update` and removes unnecessary calls to `UpdateUi.confirm_extra_information` to improve API ergonomics.
> trussed.updates: Improve API ergonomics
